name: PlayerSimulator
version: 0.2.1
description: Add fake players to your minecraft server
author: CentrumGuy, Travis Watkins

main: com.CentrumGuy.PlayerSimulator.Main

commands:
  spawnbot:
    description: Spawn a fake player at a random location
    usage: /<command> [count] [radius]
    permission: playersim.spawn
  killbots:
    description: Disconnect all fake players
    permission: playersim.killbots
  killbot:
    description: Disconnect a specific fake player
    permission: playersim.killbot
  simdebug:
    description: Read server debug information
    permission: playersim.debug
  editbot:
    description: Edit a bot's properties
    permission: playersim.editbot

permissions:
  playersim:
    description: Allow a player all plugin permissions
    children:
      playersim.spawnbot:
        description: Allow a player to spawn fake players
      playersim.killbots:
        description: Allow a player to kill all fake players
      playersim.killbot:
        description: Allow a player to kill a fake player
      playersim.debug:
        description: Allow a player to look at debug information
        

